### ISSUE TITLE
LICENSE File

### ISSUE THREAD

**Issue by justusschock** [Nico-Curti/rFBP#2]
Hi, 
first I want to thank you for this incredible work.

While reviewing for JOSS (https://github.com/openjournals/joss-reviews/issues/2663), I noted that your license file is markdown and not a plain text file as required :)

**Comment by Nico-Curti** [comment]
Hi, @justusschock. Thanks for your comments.
We followed your request and we converted the LICENSE file from Markdown to plain-text.
You can find the reviewed version of the file [here](https://github.com/Nico-Curti/rFBP/blob/master/LICENSE).
Let us know if there are other issues.

**Comment by Nico-Curti** [comment]
I close the issue since the problem seems to be solved. If there are any other comments on this topic just let me know..
