### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by justusschock** [Nico-Curti/rFBP#3]
During my review for JOSS (https://github.com/openjournals/joss-reviews/issues/2663), I also found that for your C++ Code there are not always docstrings for functions. Could you maybe add these and while on it make sure they can be parsed from oxygen or whatever?

Also your Python Docstrings could be cleaned up a bit to be a bit more consistent regarding the parameter types. If you revisit them, make sure they follow the sphinx format (or some other but sphinx is really easy to use). If you want to, you could also remove the parameter types and replace them by Python's type annotations.

This is basically a preparation for #4

**Comment by Nico-Curti** [comment]
Hi @justusschock. Thanks for your comments.
We have improved the documentation following your comments. In the [last version](https://github.com/Nico-Curti/rFBP/commit/aeb2fef1d5d2bdb34cb53c3b4fc9f94cff2ffbe5) of the code we hope to have fixed all the Python docstrings and we have improved the description of the C++ APIs.
- We used sphinx for the Python documentation and doxygen for the C++ counterpart as you have suggested.
- We have also included a [small CI](https://github.com/Nico-Curti/rFBP/actions?query=workflow%3A%22rFBP+Docs+CI%22) for the documentation to check the build at every commit.
- For the parameter type we used the numpydoc [standard](https://numpydoc.readthedocs.io/en/latest/format.html).

You can find the final result of our documentation at the link: [docs](https://rfbp.readthedocs.io/en/latest/?badge=latest)

Let us know if you have any other comment or request about this topic.

**Comment by Nico-Curti** [comment]
I close the issue since the problem seems to be solved. If there are any other comments on this topic just let me know.
