### ISSUE TITLE
Functionality Documentation

### ISSUE THREAD

**Issue by justusschock** [Nico-Curti/rFBP#4]
Hi,

during my review for JOSS (https://github.com/openjournals/joss-reviews/issues/2663) I looked for what they call "functionality documentation". I was not able to find any API-Documentation on your GitHub page. Could you maybe add this?

**Comment by Nico-Curti** [comment]
Hi,
The topic of this issue is very closed to #3 , thus we could close this issue and merge the comments in #3.

**Comment by Nico-Curti** [comment]
I close the issue since the problem seems to be solved. If there are any other comments on this topic just let me know.
