### ISSUE TITLE
CONTRIBUTING.md doesn't exist

### ISSUE THREAD

**Issue by DanielLenz** [Nico-Curti/rFBP#6]
Hi! This issue is related to the JOSS review (https://github.com/openjournals/joss-reviews/issues/2663).

I noted that towards the end of the `README`, you refer to the `CONTRIBUTING.md` for instructions on how to contribute to this project, but this file doesn't exist.

The same is true for the issue template and for the PR template.

**Comment by Nico-Curti** [comment]
Hi @DanielLenz . Thanks for your comment.
We moved all the template files related to PR, issues and contributions without fixing the hyperlink.
In the latest version of the code we hope to have fixed all the references. 
If you find other broken hyperlinks, please let us know.

**Comment by DanielLenz** [comment]
Perfect, thank you!
